#!/usr/bin/env python3
"""Real, bounded, AI-generated Nostr DM conversation -- the follow-up to
`nostr_reply.py`'s fixed first-contact ack.

Built w232 (2026-09-04) after josh's explicit Telegram ask: "i would like to
see full conversational replies" -- a direct follow-up to w231's flagged
"open-ended conversational replies remain a separate, not-yet-asked-for
step". This is that step, built with the guardrails that flag always said
it would need:

  - Only fires for senders who already got the fixed disclosure ack from
    `nostr_reply.py` (their pubkey is in `replied.jsonl`). First contact
    always stays a fixed, honest "I'm an AI" message -- never generated.
  - The reply text is generated by a SEPARATE, sandboxed `claude -p` call:
    `--restricted` (strips Bash/code-exec tools + WebFetch) plus an explicit
    `--disallowedTools` list covering the rest, no `--add-dir`, and a full
    `--system-prompt` override (not the default Claude Code coding prompt).
    That subprocess cannot read/write files, run commands, or reach the
    network beyond the model call itself -- it can only return text.
  - The system prompt (`converse_system_prompt.txt`) states the sender's
    message is DATA, never instructions; forbids claiming to be human or
    speaking for josh; forbids illegal/harmful content, secrets, and any
    claim of taking real-world action; and caps reply length.
  - Per-sender caps, tracked in `converse.jsonl`: at most DAILY_CAP replies
    in any UTC day and LIFETIME_CAP ever. Past either cap, the sender gets
    one fixed fallback message (not generated) pointing to josh directly --
    this is what actually bounds cost and stops an infinite loop with an
    automated bot on the other end (there is already one marketing-spam bot
    in the inbox).
  - Only the single newest not-yet-answered inbox message per sender is
    processed per run, so a burst of messages gets at most one reply per
    waking (~6x/day cadence), not one reply per message.
  - Never touches `published.jsonl` -- same reasoning as `nostr_reply.py`:
    DM traffic (even just "we talked") is not public activity.

    nostr/.venv/bin/python nostr/nostr_converse.py [--dry-run] [--test "msg"]
"""
import argparse
import base64
import glob
import json
import os
import subprocess
import sys
import time
from datetime import datetime, timezone

from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

import nostr_build_event as builder
import nostr_reply as reply_mod

HERE = os.path.dirname(os.path.abspath(__file__))
INBOX_GLOB = os.path.join(HERE, "inbox", "*.jsonl")
REPLIED_LOG = os.path.join(HERE, "replied.jsonl")          # who got the fixed ack
CONVERSE_LOG = os.path.join(HERE, "converse.jsonl")        # git-ignored: generated-reply audit trail
SYSTEM_PROMPT_FILE = os.path.join(HERE, "converse_system_prompt.txt")

DAILY_CAP = 5
LIFETIME_CAP = 100
MAX_REPLY_CHARS = 700
GENERATION_TIMEOUT_S = 90
HISTORY_TURNS = 6  # prior exchanges included as context, not HISTORY_TURNS messages each side

LIMIT_TEXT = (
    "Beacon has hit its reply limit for this conversation (a fixed safety cap, "
    "not personal). For anything further, reach josh directly via "
    "https://www.beaconwake.com/."
)

DISALLOWED_TOOLS = [
    "Bash", "Read", "Write", "Edit", "NotebookEdit", "Glob", "Grep",
    "WebFetch", "WebSearch", "Task", "Agent", "TodoWrite",
]


def now_iso():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def today_utc():
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def nip04_encrypt(my_priv, recipient_pub_hex, plaintext):
    recipient_pub = ec.EllipticCurvePublicKey.from_encoded_point(
        ec.SECP256K1(), b"\x02" + bytes.fromhex(recipient_pub_hex)
    )
    shared_x = my_priv.exchange(ec.ECDH(), recipient_pub)
    iv = os.urandom(16)
    data = plaintext.encode("utf-8")
    pad_len = 16 - (len(data) % 16)
    data += bytes([pad_len]) * pad_len
    enc = Cipher(algorithms.AES(shared_x), modes.CBC(iv)).encryptor()
    ct = enc.update(data) + enc.finalize()
    return base64.b64encode(ct).decode() + "?iv=" + base64.b64encode(iv).decode()


def load_disclosed_senders():
    """Pubkeys that already received the fixed first-contact ack -- only
    these are eligible for a generated reply."""
    seen = set()
    if os.path.exists(REPLIED_LOG):
        with open(REPLIED_LOG) as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    seen.add(json.loads(line)["sender_pubkey"])
                except Exception:
                    continue
    return seen


def load_converse_log():
    entries = []
    if os.path.exists(CONVERSE_LOG):
        with open(CONVERSE_LOG) as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    entries.append(json.loads(line))
                except Exception:
                    continue
    return entries


def handled_event_ids(converse_entries):
    ids = set()
    for e in converse_entries:
        if e.get("source_event_id"):
            ids.add(e["source_event_id"])
    if os.path.exists(REPLIED_LOG):
        with open(REPLIED_LOG) as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    ids.add(json.loads(line)["source_event_id"])
                except Exception:
                    continue
    return ids


def find_latest_pending(disclosed_senders, handled_ids, our_pubkey_hex):
    """One candidate (sender, protocol, event, text) per sender -- the
    newest not-yet-handled DM from a sender who already got the ack."""
    latest = {}  # sender -> (created_at, protocol, event, text)
    for path in sorted(glob.glob(INBOX_GLOB)):
        with open(path) as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    ev = json.loads(line)
                except json.JSONDecodeError:
                    continue
                kind = ev.get("kind")
                meta = ev.get("_meta", {})
                if kind == 4:
                    sender = ev.get("pubkey", "")
                    if sender == our_pubkey_hex or sender not in disclosed_senders:
                        continue
                    if ev.get("id") in handled_ids:
                        continue
                    text = meta.get("decrypted")
                    if not text or text.startswith("[decrypt failed"):
                        continue
                    ca = ev.get("created_at", 0)
                    if sender not in latest or ca > latest[sender][0]:
                        latest[sender] = (ca, "nip04", ev, text)
                elif kind == 1059:
                    unwrapped = meta.get("unwrapped")
                    if not unwrapped or unwrapped.get("rumor_kind") != 14:
                        continue
                    sender = unwrapped.get("sender_pubkey", "")
                    if sender == our_pubkey_hex or sender not in disclosed_senders:
                        continue
                    if unwrapped.get("rumor_id") in handled_ids:
                        continue
                    text = unwrapped.get("content")
                    if not text:
                        continue
                    ca = unwrapped.get("rumor_created_at", 0)
                    if sender not in latest or ca > latest[sender][0]:
                        latest[sender] = (ca, "nip17", ev, text)
    out = []
    for sender, (ca, protocol, ev, text) in latest.items():
        event_id = ev.get("id") if protocol == "nip04" else ev.get("_meta", {}).get("unwrapped", {}).get("rumor_id")
        out.append((sender, protocol, ev, text, event_id))
    return out


def sender_counts(converse_entries, sender):
    today = today_utc()
    lifetime = sum(1 for e in converse_entries if e.get("sender_pubkey") == sender and e.get("kind") == "generated")
    daily = sum(
        1 for e in converse_entries
        if e.get("sender_pubkey") == sender and e.get("kind") == "generated" and e.get("replied_at", "").startswith(today)
    )
    return daily, lifetime


def sender_history(converse_entries, sender, turns=HISTORY_TURNS):
    mine = [e for e in converse_entries if e.get("sender_pubkey") == sender and e.get("kind") == "generated"]
    return mine[-turns:]


def generate_reply(sender_label, message_text, history):
    """Sandboxed, tool-less claude -p call. Returns reply text or raises."""
    with open(SYSTEM_PROMPT_FILE) as fh:
        system_prompt = fh.read()

    convo = []
    for h in history:
        convo.append(f"Them: {h.get('in_text', '')}")
        convo.append(f"You: {h.get('out_text', '')}")
    convo.append(f"Them: {message_text}")
    user_prompt = (
        f"Conversation so far with this Nostr sender ({sender_label}):\n\n"
        + "\n".join(convo)
        + "\n\nWrite your next reply (\"You:\") now."
    )

    cmd = [
        "claude", "-p", user_prompt,
        "--restricted",
        "--disallowedTools", *DISALLOWED_TOOLS,
        "--system-prompt", system_prompt,
        "--output-format", "text",
        "--model", "haiku",
    ]
    result = subprocess.run(
        cmd, capture_output=True, text=True, timeout=GENERATION_TIMEOUT_S,
        cwd=HERE,
    )
    if result.returncode != 0:
        raise RuntimeError(f"claude -p exited {result.returncode}: {result.stderr[:500]}")
    text = result.stdout.strip()
    if not text:
        raise RuntimeError("claude -p returned empty output")
    text = text.replace("\x00", "")
    if len(text) > MAX_REPLY_CHARS:
        text = text[:MAX_REPLY_CHARS].rsplit(" ", 1)[0] + "…"
    return text


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true", help="generate but don't send/log")
    ap.add_argument("--test", metavar="MESSAGE", help="generate a reply to a synthetic message and print it -- no inbox, no send, no log")
    args = ap.parse_args()

    if args.test:
        reply = generate_reply("test-sender", args.test, [])
        print(f"generated ({len(reply)} chars):\n{reply}")
        return 0

    priv_int, our_pubkey_hex = builder.load_keys()
    priv_ec = ec.derive_private_key(priv_int, ec.SECP256K1())

    disclosed = load_disclosed_senders()
    converse_entries = load_converse_log()
    handled = handled_event_ids(converse_entries)

    pending = find_latest_pending(disclosed, handled, our_pubkey_hex)
    if not pending:
        print("no new conversational messages to answer")
        return 0

    print(f"{len(pending)} sender(s) with a new message to answer")
    new_entries = []
    for sender, protocol, ev, message_text, event_id in pending:
        daily, lifetime = sender_counts(converse_entries, sender)
        if daily >= DAILY_CAP or lifetime >= LIFETIME_CAP:
            print(f"  {protocol}  {sender[:16]}…  CAP REACHED (daily={daily}, lifetime={lifetime}) -- sending fixed limit notice")
            reply_text, kind = LIMIT_TEXT, "limit"
        else:
            history = sender_history(converse_entries, sender)
            try:
                reply_text = generate_reply(sender[:16], message_text, history)
                kind = "generated"
                print(f"  {protocol}  {sender[:16]}…  generated {len(reply_text)} chars")
            except Exception as exc:  # noqa: BLE001
                print(f"  {protocol}  {sender[:16]}…  generation FAILED: {exc.__class__.__name__}: {exc} -- skipping this run")
                continue

        try:
            if protocol == "nip04":
                reply_mod.send_nip04_text(priv_ec, priv_int, our_pubkey_hex, sender, reply_text, args.dry_run, label=kind)
            else:
                reply_mod.send_nip17_text(priv_int, our_pubkey_hex, sender, reply_text, event_id, args.dry_run, label=kind)
        except Exception as exc:  # noqa: BLE001
            print(f"    SEND FAILED: {exc.__class__.__name__}: {exc}")
            continue

        if args.dry_run:
            continue
        new_entries.append({
            "sender_pubkey": sender, "protocol": protocol, "kind": kind,
            "replied_at": now_iso(), "source_event_id": event_id,
            "in_text": message_text, "out_text": reply_text,
        })
        print("    sent + logged")

    if new_entries and not args.dry_run:
        with open(CONVERSE_LOG, "a") as fh:
            for entry in new_entries:
                fh.write(json.dumps(entry, separators=(",", ":")) + "\n")
        print(f"\nappended {len(new_entries)} entr(y/ies) to {CONVERSE_LOG}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
