#!/usr/bin/env python3
"""Localize the site's Google Fonts into website/fonts/ (latin + latin-ext only).

Fetches the exact css2 the pages used, downloads each referenced woff2, rewrites
src: url() to a local /fonts/ path, and writes website/fonts/fonts.css. Space
Grotesk and IBM Plex Sans are shipped by Google as single variable woff2 files
(one file covers every weight); IBM Plex Mono is static (one file per weight).
Re-run when the weight set in the <link> changes. Idempotent.
"""
import re, urllib.request, pathlib, hashlib

CSS2 = ("https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700"
        "&family=IBM+Plex+Sans:wght@300;400;500;600"
        "&family=IBM+Plex+Mono:wght@400;500&display=swap")
UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) "
      "Chrome/126.0.0.0 Safari/537.36")
KEEP = {"latin", "latin-ext"}
HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE / "fonts"

def get(url):
    return urllib.request.urlopen(
        urllib.request.Request(url, headers={"User-Agent": UA}), timeout=30).read()

def main():
    OUT.mkdir(exist_ok=True)
    css = get(CSS2).decode()
    # how many distinct weights cite each woff2 url -> variable if >1
    url_weights = {}
    for blk in re.split(r'(?=/\* )', css):
        sub = re.match(r'/\* ([a-z-]+) \*/', blk.strip())
        if not sub or sub.group(1) not in KEEP:
            continue
        u = re.search(r'src: url\((https://\S+\.woff2)\)', blk).group(1)
        w = re.search(r'font-weight: (\d+)', blk).group(1)
        url_weights.setdefault(u, set()).add(w)

    names, out = {}, []
    for blk in re.split(r'(?=/\* )', css):
        sub = re.match(r'/\* ([a-z-]+) \*/', blk.strip())
        if not sub or sub.group(1) not in KEEP:
            continue
        subset = sub.group(1)
        fam = re.search(r"font-family: '([^']+)'", blk).group(1)
        wght = re.search(r'font-weight: (\d+)', blk).group(1)
        url = re.search(r'src: url\((https://\S+\.woff2)\)', blk).group(1)
        if url not in names:
            slug = fam.lower().replace(" ", "-")
            tag = "variable" if len(url_weights[url]) > 1 else wght
            fname = f"{slug}-{tag}-{subset}.woff2"
            data = get(url)
            (OUT / fname).write_bytes(data)
            names[url] = fname
            print(f"  {fname:36s} {len(data):>7,} B  sha1={hashlib.sha1(data).hexdigest()[:12]}")
        out.append(blk.replace(url, f"/fonts/{names[url]}").rstrip() + "\n")

    hdr = ("/* Self-hosted web fonts, latin + latin-ext subsets. Generated by\n"
           "   website/localize_fonts.py from the Google Fonts css2 API. Weights:\n"
           "   Space Grotesk 400/500/600/700, IBM Plex Sans 300/400/500/600,\n"
           "   IBM Plex Mono 400/500. font-display: swap. Do not hand-edit. */\n\n")
    (OUT / "fonts.css").write_text(hdr + "".join(out))
    print(f"wrote {OUT/'fonts.css'} ({len(out)} @font-face blocks, {len(names)} files)")

if __name__ == "__main__":
    main()
